global:
  resolve_timeout: 5m
  smtp_from: alerts@lead-scraper.your-domain.com
  smtp_smarthost: ${ALERT_SMTP_HOST}:${ALERT_SMTP_PORT}
  smtp_auth_username: ${ALERT_SMTP_USER}
  smtp_auth_password: ${ALERT_SMTP_PASSWORD}
  smtp_require_tls: true

route:
  receiver: default
  group_by: ['alertname', 'environment']
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - match:
        severity: critical
      receiver: critical-alerts
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: warning-alerts
      repeat_interval: 6h
    - match:
        severity: info
      receiver: info-alerts
      repeat_interval: 24h

receivers:
  - name: default
    email_configs:
      - to: ${ALERT_EMAIL_TO}
        html: '{{ template "email.html" . }}'
        text: '{{ template "email.text" . }}'
        require_tls: true

  - name: critical-alerts
    email_configs:
      - to: ${ALERT_EMAIL_TO}
        html: '{{ template "email.html" . }}'
        text: '{{ template "email.text" . }}'
        require_tls: true
    slack_configs:
      - api_url: ${ALERT_SLACK_WEBHOOK_URL}
        send_resolved: true
        channel: ${ALERT_SLACK_CHANNEL}
        username: ${ALERT_SLACK_USERNAME}
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        color: '{{ template "slack.color" . }}'

  - name: warning-alerts
    email_configs:
      - to: ${ALERT_EMAIL_TO}
        html: '{{ template "email.html" . }}'
        text: '{{ template "email.text" . }}'
        require_tls: true
    slack_configs:
      - api_url: ${ALERT_SLACK_WEBHOOK_URL}
        send_resolved: true
        channel: ${ALERT_SLACK_CHANNEL}
        username: ${ALERT_SLACK_USERNAME}
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        color: '{{ template "slack.color" . }}'

  - name: info-alerts
    slack_configs:
      - api_url: ${ALERT_SLACK_WEBHOOK_URL}
        send_resolved: true
        channel: ${ALERT_SLACK_CHANNEL}
        username: ${ALERT_SLACK_USERNAME}
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        color: '{{ template "slack.color" . }}'

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'environment']

  - source_match:
      severity: warning
    target_match:
      severity: info
    equal: ['alertname', 'environment']

templates:
  - '/etc/alertmanager/templates/email.tmpl'
  - '/etc/alertmanager/templates/slack.tmpl'
