"""initial_schema

Revision ID: e65490fa834a
Revises: 
Create Date: 2025-10-17 13:58:34.830790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65490fa834a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_form', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('directors', sa.JSON(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('team_members', sa.JSON(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('google_reviews_count', sa.Integer(), nullable=True),
    sa.Column('google_opening_hours', sa.JSON(), nullable=True),
    sa.Column('register_number', sa.String(length=100), nullable=True),
    sa.Column('register_court', sa.String(length=100), nullable=True),
    sa.Column('register_data', sa.JSON(), nullable=True),
    sa.Column('lead_status', sa.Enum('NEW', 'QUALIFIED', 'CONTACTED', 'CONVERTED', 'REJECTED', name='leadstatus'), nullable=True),
    sa.Column('lead_quality', sa.Enum('A', 'B', 'C', 'D', 'UNKNOWN', name='leadquality'), nullable=True),
    sa.Column('lead_score', sa.Float(), nullable=True),
    sa.Column('first_scraped_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_city'), 'companies', ['city'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=False)
    op.create_index(op.f('ix_companies_google_place_id'), 'companies', ['google_place_id'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_is_duplicate'), 'companies', ['is_duplicate'], unique=False)
    op.create_index(op.f('ix_companies_lead_quality'), 'companies', ['lead_quality'], unique=False)
    op.create_index(op.f('ix_companies_lead_status'), 'companies', ['lead_status'], unique=False)
    op.create_index(op.f('ix_companies_postal_code'), 'companies', ['postal_code'], unique=False)
    op.create_index(op.f('ix_companies_register_number'), 'companies', ['register_number'], unique=False)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('company_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_notes_company_id'), 'company_notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_notes_id'), 'company_notes', ['id'], unique=False)
    op.create_table('company_sources',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'source_id')
    )
    op.create_table('duplicate_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_a_id', sa.Integer(), nullable=False),
    sa.Column('company_b_id', sa.Integer(), nullable=False),
    sa.Column('name_similarity', sa.Float(), nullable=True),
    sa.Column('address_similarity', sa.Float(), nullable=True),
    sa.Column('phone_similarity', sa.Float(), nullable=True),
    sa.Column('website_similarity', sa.Float(), nullable=True),
    sa.Column('overall_similarity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_a_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['company_b_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_candidates_company_a_id'), 'duplicate_candidates', ['company_a_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_company_b_id'), 'duplicate_candidates', ['company_b_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_id'), 'duplicate_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_overall_similarity'), 'duplicate_candidates', ['overall_similarity'], unique=False)
    op.create_table('scraping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('search_query', sa.String(length=500), nullable=True),
    sa.Column('max_pages', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('new_companies', sa.Integer(), nullable=True),
    sa.Column('updated_companies', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_jobs_city'), 'scraping_jobs', ['city'], unique=False)
    op.create_index(op.f('ix_scraping_jobs_created_at'), 'scraping_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scraping_jobs_id'), 'scraping_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_scraping_jobs_status'), 'scraping_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraping_jobs_status'), table_name='scraping_jobs')
    op.drop_index(op.f('ix_scraping_jobs_id'), table_name='scraping_jobs')
    op.drop_index(op.f('ix_scraping_jobs_created_at'), table_name='scraping_jobs')
    op.drop_index(op.f('ix_scraping_jobs_city'), table_name='scraping_jobs')
    op.drop_table('scraping_jobs')
    op.drop_index(op.f('ix_duplicate_candidates_overall_similarity'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_company_b_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_company_a_id'), table_name='duplicate_candidates')
    op.drop_table('duplicate_candidates')
    op.drop_table('company_sources')
    op.drop_index(op.f('ix_company_notes_id'), table_name='company_notes')
    op.drop_index(op.f('ix_company_notes_company_id'), table_name='company_notes')
    op.drop_table('company_notes')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_companies_website'), table_name='companies')
    op.drop_index(op.f('ix_companies_register_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_postal_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_lead_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_lead_quality'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_duplicate'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_google_place_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_city'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
