groups:
  - name: scraping_jobs
    rules:
      - alert: HighScrapingFailureRate
        expr: |
          sum(rate(scraping_jobs_total{status="failed"}[5m]))
            /
          sum(rate(scraping_jobs_total[5m]))
            > 0.20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High scraping failure rate: {{ $value | humanizePercentage }}"
          description: |
            More than 20% of scraping jobs are failing in the last 5 minutes.
            Investigate worker logs and recent deployments.
          dashboard: "{{ $labels.source }}"

      - alert: ScrapingJobStuck
        expr: |
          scraping_jobs_active > 0 and rate(scraping_jobs_total[10m]) == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Scraping jobs stuck - no completions in 10 minutes"
          description: |
            Active scraping jobs detected but no jobs have completed in the
            last 10 minutes. Workers might be stuck or external dependencies
            may be unavailable.

      - alert: NoScrapingJobsCompleted
        expr: |
          sum(increase(scraping_jobs_total{status="completed"}[1h])) == 0
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: "No scraping jobs completed in last hour"
          description: |
            No successful scraping jobs have completed in the past hour.
            Check worker status, queue backlog, and external sources.

      - alert: HighScrapingErrorRate
        expr: |
          sum(rate(scraping_results_total{result_type="errors"}[5m]))
            /
          sum(rate(scraping_results_total[5m]))
            > 0.10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High scraping error rate: {{ $value | humanizePercentage }}"
          description: |
            More than 10% of scraping results are errors in the last 5 minutes.
            Review source websites and error logs for details.

      - alert: QueueBacklogHigh
        expr: queue_size{queue_name="scraping"} > 100
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Scraping queue backlog: {{ $value }} jobs"
          description: |
            The scraping queue has more than 100 pending jobs for over 10 minutes.
            Consider scaling workers or investigating slow-running jobs.
